"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Environ 설정
env = environ.Env(
    # 기본값 설정, 필수 항목이면 False
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경변수는 Docker Compose에서 주입됨 (--env-file 옵션 사용)
# environ.Env.read_env() 주석 처리 - Docker 환경변수 우선 사용

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key-only-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # CORS 설정 추가
    'apps.db.apps.DbConfig',
    'apps.api.apps.ApiConfig',
    # pgvector 지원을 위한 추가 앱들
    'pgvector',  # pgvector Django 확장
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 (다른 미들웨어보다 앞에 위치해야 함)
    'core.middleware.RequestLoggingMiddleware',  # 요청 로깅 미들웨어 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS 설정
CORS_ALLOW_ALL_ORIGINS = True  # 개발 환경에서는 모든 도메인에서의 요청 허용
# 프로덕션 환경에서는 아래와 같이 특정 도메인만 허용하는 것이 좋습니다
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "https://yourdomain.com",
# ]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 데이터베이스 URL 우선 사용 (클라우드 환경)
DATABASE_URL = env('DATABASE_URL', default=None)

if DATABASE_URL:
    # 클라우드 환경: DATABASE_URL 사용
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # 로컬 환경: 개별 환경변수 사용
    DATABASES = {
        'default': {
            'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': env('DB_NAME', default='capstone_local'),        
            'USER': env('DB_USER', default='capstone_user'),      
            'PASSWORD': env('DB_PASSWORD', default='local_password'),  
            'HOST': env('DB_HOST', default='db'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }

# 연결 풀링 설정 (프로덕션 환경용)
DATABASES['default']['CONN_MAX_AGE'] = env('DB_CONN_MAX_AGE', default=600, cast=int)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 정적 파일이 수집될 디렉토리

# 추가 정적 파일 디렉토리 (개발 환경용)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 미디어 파일 설정 (사용자 업로드 파일)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# AWS 설정
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default=None)
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='capstone-dev-raw')
AWS_S3_REGION_NAME = env('AWS_DEFAULT_REGION', default='ap-northeast-2')
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default=None)

# S3 버킷 이름 설정
AWS_RAW_BUCKET_NAME = env('AWS_RAW_BUCKET_NAME', default='capstone-dev-raw')
AWS_THUMBNAILS_BUCKET_NAME = env('AWS_THUMBNAILS_BUCKET_NAME', default='capstone-dev-thumbnails')
AWS_HIGHLIGHTS_BUCKET_NAME = env('AWS_HIGHLIGHTS_BUCKET_NAME', default='capstone-dev-highlights')

# 파일 저장소 설정 (AWS S3 vs 로컬)
USE_S3 = bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME)

if USE_S3:
    # AWS S3 스토리지 설정
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.StaticS3Boto3Storage'
    
    # S3 설정
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # 1시간
    
    # S3 URL 설정
    if AWS_S3_CUSTOM_DOMAIN:
        STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    else:
        STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/static/'
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/'
else:
    # 로컬 파일 스토리지 설정
    STATIC_URL = 'static/'
    MEDIA_URL = '/media/'

# 메타데이터 및 썸네일 파일 경로 설정
PROJECT_ROOT = BASE_DIR.parent  # /home/uns/code/project
UPLOADS_BASE_DIR = env('UPLOADS_BASE_DIR', default='front/public/uploads')  # front/public/uploads
METADATA_SUBDIR = env('METADATA_SUBDIR', default='metadata')  # metadata
THUMBNAIL_SUBDIR = env('THUMBNAIL_SUBDIR', default='thumbnails')  # thumbnails
VIDEO_SUBDIR = env('VIDEO_SUBDIR', default='videos')  # videos

# 실제 파일 경로들
METADATA_DIR = os.path.join(PROJECT_ROOT, UPLOADS_BASE_DIR, METADATA_SUBDIR)
THUMBNAIL_DIR = os.path.join(PROJECT_ROOT, UPLOADS_BASE_DIR, THUMBNAIL_SUBDIR)
VIDEO_DIR = os.path.join(PROJECT_ROOT, UPLOADS_BASE_DIR, VIDEO_SUBDIR)

# OpenAI 설정 (RAG 기능용)
OPENAI_API_KEY = env('OPENAI_API_KEY', default=None)
OPENAI_MODEL = env('OPENAI_MODEL', default='gpt-3.5-turbo')
OPENAI_EMBEDDING_MODEL = env('OPENAI_EMBEDDING_MODEL', default='text-embedding-ada-002')

# AWS Bedrock 설정
AWS_BEDROCK_REGION = env('AWS_BEDROCK_REGION', default='ap-northeast-2')
AWS_BEDROCK_MODEL_ID = env('AWS_BEDROCK_MODEL_ID', default='anthropic.claude-3-sonnet-20240229-v1:0')
AWS_BEDROCK_EMBEDDING_MODEL_ID = env('AWS_BEDROCK_EMBEDDING_MODEL_ID', default='amazon.titan-embed-text-v1')
AWS_BEDROCK_KNOWLEDGE_BASE_ID = env('AWS_BEDROCK_KNOWLEDGE_BASE_ID', default=None)
USE_BEDROCK = env('USE_BEDROCK', default='true').lower() == 'true'

# Video Analysis FastAPI 설정 (ECS Service Discovery DNS)
VIDEO_ANALYSIS_URL = env('VIDEO_ANALYSIS_URL', default=None)  # 예: http://video-analysis.capstone.local:7000

# 하이브리드 RAG 설정 (Text2SQL + pgvector)
USE_HYBRID_SEARCH = env('USE_HYBRID_SEARCH', default='true').lower() == 'true'
VECTOR_SEARCH_SIMILARITY_THRESHOLD = env('VECTOR_SEARCH_SIMILARITY_THRESHOLD', default=0.3, cast=float)
HYBRID_SEARCH_LIMIT = env('HYBRID_SEARCH_LIMIT', default=5, cast=int)

# 벡터 검색 설정
VECTOR_DIMENSION = env('VECTOR_DIMENSION', default=1536, cast=int)  # OpenAI ada-002
VECTOR_SIMILARITY_THRESHOLD = env('VECTOR_SIMILARITY_THRESHOLD', default=0.8, cast=float)
VECTOR_SEARCH_LIMIT = env('VECTOR_SEARCH_LIMIT', default=10, cast=int)

# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CSRF 설정 (API에서는 비활성화)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8088',
    'http://127.0.0.1:8088',
    'http://host.docker.internal:8088',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 대용량 파일 업로드를 위한 설정
# 파일 업로드 크기 제한 (10GB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB

# 요청 크기 제한 (10GB)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_NUMBER_FILES = 1000

# 타임아웃 설정 (600초 = 10분)
CONN_MAX_AGE = 600

# 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.middleware': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
