# Generated by Django 5.2 on 2025-10-27 07:14

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("person_enter", "사람 입장"),
                            ("person_exit", "사람 퇴장"),
                            ("interaction", "상호작용"),
                            ("anomaly", "이상행동"),
                            ("demographic_change", "인구통계 변화"),
                            ("picking", "물건 집기"),
                            ("walking", "걷기"),
                            ("standing", "서있기"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("duration", models.FloatField(default=0.0)),
                ("frame_number", models.IntegerField()),
                ("bbox_x", models.IntegerField(default=0)),
                ("bbox_y", models.IntegerField(default=0)),
                ("bbox_width", models.IntegerField(default=0)),
                ("bbox_height", models.IntegerField(default=0)),
                ("age_group", models.CharField(blank=True, max_length=20)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("emotion", models.CharField(blank=True, max_length=20)),
                ("action", models.CharField(blank=True, max_length=100)),
                ("interaction_target", models.CharField(blank=True, max_length=100)),
                ("confidence", models.FloatField(default=0.0)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("searchable_text", models.TextField(blank=True)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "data_tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("search_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["video", "timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        blank=True, help_text="When video was recorded", null=True
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                (
                    "frame_rate",
                    models.FloatField(
                        blank=True, help_text="Frames per second", null=True
                    ),
                ),
                (
                    "fps",
                    models.FloatField(
                        blank=True, help_text="Frames per second", null=True
                    ),
                ),
                (
                    "resolution_width",
                    models.IntegerField(
                        blank=True, help_text="Video width in pixels", null=True
                    ),
                ),
                (
                    "resolution_height",
                    models.IntegerField(
                        blank=True, help_text="Video height in pixels", null=True
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Video width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Video height in pixels", null=True
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(default="capstone-video-bucket", max_length=63),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="Primary S3 object key", max_length=1024
                    ),
                ),
                (
                    "s3_raw_key",
                    models.CharField(help_text="S3 raw video key", max_length=500),
                ),
                (
                    "s3_result_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 analysis result key",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("thumbnail_s3_key", models.CharField(blank=True, max_length=1024)),
                (
                    "s3_thumbnail_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 thumbnail key",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("metadata_extracted", models.BooleanField(default=False)),
                (
                    "metadata_extraction_job_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("processing", "분석중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "analysis_progress",
                    models.IntegerField(default=0, help_text="Analysis progress 0-100"),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        help_text="AWS Batch job ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("search_count", models.IntegerField(default=0)),
                (
                    "total_searches",
                    models.IntegerField(
                        default=0, help_text="Total times this video was searched"
                    ),
                ),
                ("last_accessed", models.DateTimeField(auto_now_add=True)),
                ("last_searched", models.DateTimeField(blank=True, null=True)),
                ("hotness_score", models.FloatField(default=0.0)),
                (
                    "data_tier",
                    models.CharField(
                        choices=[
                            ("hot", "Hot - 자주 접근"),
                            ("warm", "Warm - 가끔 접근"),
                            ("cold", "Cold - 거의 접근 안함"),
                        ],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("warm_s3_key", models.CharField(blank=True, max_length=1024)),
                ("cold_s3_key", models.CharField(blank=True, max_length=1024)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["data_tier", "hotness_score"],
                        name="db_video_data_ti_da483b_idx",
                    ),
                    models.Index(
                        fields=["search_count", "last_accessed"],
                        name="db_video_search__985857_idx",
                    ),
                    models.Index(
                        fields=["metadata_extracted"],
                        name="db_video_metadat_41ea96_idx",
                    ),
                    models.Index(
                        fields=["analysis_status"], name="db_video_analysi_6cf323_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=255)),
                ("session_name", models.CharField(blank=True, max_length=255)),
                ("session_summary", models.TextField(blank=True)),
                ("total_interactions", models.IntegerField(default=0)),
                (
                    "search_queries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("context_summary", models.TextField(blank=True)),
                (
                    "context_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "진행중"),
                            ("completed", "완료"),
                            ("abandoned", "중단됨"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                (
                    "data_tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("access_count", models.IntegerField(default=0)),
                (
                    "main_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.event",
                    ),
                ),
                ("related_videos", models.ManyToManyField(blank=True, to="db.video")),
            ],
            options={
                "ordering": ["-last_interaction"],
            },
        ),
        migrations.CreateModel(
            name="PromptInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_id", models.CharField(max_length=255)),
                ("sequence_number", models.IntegerField()),
                ("user_prompt", models.TextField()),
                ("user_intent", models.CharField(blank=True, max_length=100)),
                ("ai_response", models.TextField()),
                ("response_summary", models.CharField(blank=True, max_length=500)),
                ("analysis_type", models.CharField(blank=True, max_length=50)),
                ("analysis_results", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "thumbnail_s3_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        help_text="생성된 썸네일의 S3 경로들",
                        size=None,
                    ),
                ),
                ("vlm_analysis", models.JSONField(blank=True, default=dict)),
                (
                    "visual_elements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="감지된 시각적 요소들",
                        size=None,
                    ),
                ),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "response_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("processing_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_events", models.ManyToManyField(blank=True, to="db.event")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="db.promptsession",
                    ),
                ),
                ("related_videos", models.ManyToManyField(blank=True, to="db.video")),
            ],
            options={
                "ordering": ["session", "sequence_number"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="db.video",
            ),
        ),
        migrations.CreateModel(
            name="DisplayData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_index", models.IntegerField()),
                ("image_name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("original_width", models.IntegerField()),
                ("original_height", models.IntegerField()),
                ("new_width", models.IntegerField()),
                ("new_height", models.IntegerField()),
                ("width_ratio", models.FloatField()),
                ("height_ratio", models.FloatField()),
                ("mask_key", models.IntegerField()),
                ("avg_depth", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                ("min_x", models.IntegerField()),
                ("max_x", models.IntegerField()),
                ("min_y", models.IntegerField()),
                ("max_y", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("mask_image_s3_key", models.CharField(blank=True, max_length=1024)),
                (
                    "data_tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="display_data",
                        to="db.video",
                    ),
                ),
            ],
            options={
                "ordering": ["video", "timestamp", "image_index", "mask_key"],
            },
        ),
        migrations.CreateModel(
            name="DepthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_name", models.CharField(max_length=255)),
                ("frame_number", models.IntegerField()),
                ("frame_timestamp", models.FloatField()),
                ("frame_width", models.IntegerField()),
                ("frame_height", models.IntegerField()),
                ("mask_id", models.IntegerField()),
                ("bbox_x1", models.IntegerField()),
                ("bbox_y1", models.IntegerField()),
                ("bbox_x2", models.IntegerField()),
                ("bbox_y2", models.IntegerField()),
                ("area", models.IntegerField()),
                ("avg_depth", models.FloatField()),
                ("min_depth", models.FloatField()),
                ("max_depth", models.FloatField()),
                ("depth_variance", models.FloatField(default=0.0)),
                ("depth_map_s3_key", models.CharField(blank=True, max_length=1024)),
                (
                    "data_tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depth_data",
                        to="db.video",
                    ),
                ),
            ],
            options={
                "ordering": ["video", "frame_timestamp", "mask_id"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("job_name", models.CharField(max_length=255)),
                ("job_queue", models.CharField(max_length=255)),
                ("job_definition", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "제출됨"),
                            ("pending", "대기중"),
                            ("runnable", "실행가능"),
                            ("starting", "시작중"),
                            ("running", "실행중"),
                            ("succeeded", "성공"),
                            ("failed", "실패"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                (
                    "analysis_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="수행할 분석 유형들",
                        size=None,
                    ),
                ),
                ("result_s3_key", models.CharField(blank=True, max_length=1024)),
                ("log_s3_key", models.CharField(blank=True, max_length=1024)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_jobs",
                        to="db.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("object_detection", "객체 감지"),
                            ("action_recognition", "행동 인식"),
                            ("scene_analysis", "장면 분석"),
                            ("demographic_analysis", "인구통계 분석"),
                            ("anomaly_detection", "이상 감지"),
                            ("depth_analysis", "깊이 분석"),
                            ("display_analysis", "진열대 분석"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("confidence", models.FloatField()),
                ("result_data", models.JSONField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("searchable_text", models.TextField()),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="hot",
                        max_length=10,
                    ),
                ),
                ("search_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="db.video",
                    ),
                ),
            ],
            options={
                "ordering": ["video", "timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="promptsession",
            index=models.Index(
                fields=["session_id"], name="db_promptse_session_7a92c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptsession",
            index=models.Index(
                fields=["user_id", "status"], name="db_promptse_user_id_c968c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptsession",
            index=models.Index(
                fields=["main_event"], name="db_promptse_main_ev_4316a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptsession",
            index=models.Index(
                fields=["data_tier", "access_count"],
                name="db_promptse_data_ti_016f53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptinteraction",
            index=models.Index(
                fields=["session", "sequence_number"],
                name="db_promptin_session_b2db6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptinteraction",
            index=models.Index(
                fields=["user_intent"], name="db_promptin_user_in_5b05c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptinteraction",
            index=models.Index(
                fields=["analysis_type"], name="db_promptin_analysi_6bc2e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptinteraction",
            index=models.Index(
                fields=["confidence_score"], name="db_promptin_confide_2e9bdb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promptinteraction",
            unique_together={("session", "sequence_number")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["video", "event_type"], name="db_event_video_i_d1f648_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["timestamp"], name="db_event_timesta_132ec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["age_group", "gender"], name="db_event_age_gro_48dfb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["data_tier", "search_count"], name="db_event_data_ti_8f7e8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="displaydata",
            index=models.Index(
                fields=["video", "timestamp"], name="db_displayd_video_i_8258b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="displaydata",
            index=models.Index(
                fields=["image_index"], name="db_displayd_image_i_55538c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="displaydata",
            index=models.Index(
                fields=["avg_depth"], name="db_displayd_avg_dep_31f500_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="displaydata",
            index=models.Index(
                fields=["description"], name="db_displayd_descrip_f4976d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="displaydata",
            index=models.Index(
                fields=["data_tier"], name="db_displayd_data_ti_d69672_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="displaydata",
            unique_together={("video", "image_index", "mask_key")},
        ),
        migrations.AddIndex(
            model_name="depthdata",
            index=models.Index(
                fields=["video", "frame_timestamp"],
                name="db_depthdat_video_i_a7cf99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="depthdata",
            index=models.Index(
                fields=["frame_name"], name="db_depthdat_frame_n_f7fb7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depthdata",
            index=models.Index(
                fields=["avg_depth"], name="db_depthdat_avg_dep_3d9da6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depthdata",
            index=models.Index(
                fields=["data_tier"], name="db_depthdat_data_ti_c52a44_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="depthdata",
            unique_together={("video", "frame_name", "mask_id")},
        ),
        migrations.AddIndex(
            model_name="analysisjob",
            index=models.Index(fields=["status"], name="db_analysis_status_0da8ca_idx"),
        ),
        migrations.AddIndex(
            model_name="analysisjob",
            index=models.Index(
                fields=["video", "status"], name="db_analysis_video_i_93672b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoanalysis",
            index=models.Index(
                fields=["video", "analysis_type"], name="db_videoana_video_i_a1b59e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoanalysis",
            index=models.Index(
                fields=["timestamp"], name="db_videoana_timesta_c98c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoanalysis",
            index=models.Index(
                fields=["confidence"], name="db_videoana_confide_c6d06c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoanalysis",
            index=models.Index(
                fields=["data_tier", "search_count"],
                name="db_videoana_data_ti_862ba8_idx",
            ),
        ),
    ]
