# Generated by Django 5.2 on 2025-04-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('obj_id', models.IntegerField()),
                ('age', models.FloatField()),
                ('gender', models.CharField(max_length=10, null=True)),
                ('gender_score', models.FloatField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('area_of_interest', models.IntegerField()),
                ('action_detected', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PromptInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_prompt', models.TextField()),
                ('output_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('action_sequence', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.event')),
            ],
        ),
    ]
