# Generated by Django 5.2 on 2025-06-03 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_prompt', models.TextField(blank=True)),
                ('last_response', models.TextField(blank=True)),
                ('interaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='prompthistory',
            name='main_event',
        ),
        migrations.RemoveField(
            model_name='prompthistory',
            name='video',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='event',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['video', 'timestamp']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='upload_time',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='promptinteraction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_path',
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='found_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='generated_sql',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='highlight_thumbnail_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='processing_status',
            field=models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='thumbnail_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='timeline_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='video',
            field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_interactions', to='db.video'),
        ),
        migrations.AddField(
            model_name='video',
            name='chat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='major_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.BigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gender_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['video', 'timestamp'], name='db_event_video_i_0ff3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='db_event_event_t_404a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='db_event_timesta_132ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['upload_date'], name='db_video_upload__bc55e1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['name'], name='db_video_name_7f22a1_idx'),
        ),
        migrations.AddField(
            model_name='promptsession',
            name='main_event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_sessions', to='db.event'),
        ),
        migrations.AddField(
            model_name='promptsession',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_sessions', to='db.video'),
        ),
        migrations.AlterField(
            model_name='promptinteraction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='db.promptsession'),
        ),
        migrations.AddIndex(
            model_name='promptinteraction',
            index=models.Index(fields=['session', 'timestamp'], name='db_promptin_session_db9f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='promptinteraction',
            index=models.Index(fields=['video', 'timestamp'], name='db_promptin_video_i_4bd5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='promptinteraction',
            index=models.Index(fields=['processing_status'], name='db_promptin_process_81aad7_idx'),
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['video', '-updated_at'], name='db_promptse_video_i_2451f8_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['-created_at'], name='db_promptse_created_965c2e_idx'),
        ),
        migrations.DeleteModel(
            name='PromptHistory',
        ),
    ]
