# Generated by Django 5.2 on 2025-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promptinteraction',
            old_name='user_id',
            new_name='prompt_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='action_detected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
