# Generated by Django 5.2 on 2025-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="summary",
            field=models.TextField(
                blank=True, help_text="AI 영상 요약 (VLM 생성)", null=True
            ),
        ),
    ]
