# Generated by Django 5.2 on 2025-05-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_user_id_promptinteraction_prompt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptinteraction',
            name='main_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_interactions', to='db.event'),
        ),
    ]
