# Generated by manual creation on 2025-10-27 (Event 모델에 S3 썸네일 필드 추가)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_video_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="s3_thumbnail_bucket",
            field=models.CharField(
                default="capstone-dev-thumbnails",
                help_text="썸네일 이미지가 저장된 S3 버킷",
                max_length=63,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="s3_thumbnail_key",
            field=models.CharField(
                blank=True,
                help_text="썸네일 이미지의 S3 객체 키 (예: events/event_001/frame_1234.jpg)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="thumbnail_uploaded_at",
            field=models.DateTimeField(
                blank=True, help_text="썸네일이 S3에 업로드된 시각", null=True
            ),
        ),
    ]
