# Generated by Django 5.2 on 2025-06-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_promptsession_remove_prompthistory_main_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='orientataion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scene_analysis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='gender_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
