# Generated by Django 5.2 on 2025-05-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_promptinteraction_main_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptinteraction',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='promptinteraction',
            old_name='main_event',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='promptinteraction',
            name='prompt_id',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='db.event'),
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_histories', to='db.event')),
            ],
        ),
        migrations.AddField(
            model_name='promptinteraction',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='db.prompthistory'),
            preserve_default=False,
        ),
    ]
