# Generated by Django 5.2 on 2026-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_event_thumbnail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary_status',
            field=models.CharField(
                max_length=20,
                default='pending',
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed')
                ],
                help_text='영상 요약 생성 상태'
            ),
        ),
    ]
