# Generated by Django 5.2 on 2025-06-04 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_event_orientataion_event_scene_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(max_length=255)),
                ('frame_width', models.IntegerField()),
                ('frame_height', models.IntegerField()),
                ('mask_id', models.IntegerField()),
                ('bbox_x1', models.IntegerField()),
                ('bbox_y1', models.IntegerField()),
                ('bbox_x2', models.IntegerField()),
                ('bbox_y2', models.IntegerField()),
                ('area', models.IntegerField()),
                ('avg_depth', models.FloatField()),
                ('min_depth', models.FloatField()),
                ('max_depth', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_data', to='db.video')),
            ],
            options={
                'ordering': ['video', 'frame_name', 'mask_id'],
                'indexes': [models.Index(fields=['video', 'frame_name'], name='db_depthdat_video_i_9ce6c9_idx'), models.Index(fields=['frame_name'], name='db_depthdat_frame_n_f7fb7a_idx'), models.Index(fields=['video', 'mask_id'], name='db_depthdat_video_i_e74d87_idx')],
                'unique_together': {('frame_name', 'mask_id')},
            },
        ),
        migrations.CreateModel(
            name='DisplayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_index', models.IntegerField()),
                ('image_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('original_width', models.IntegerField()),
                ('original_height', models.IntegerField()),
                ('new_width', models.IntegerField()),
                ('new_height', models.IntegerField()),
                ('width_ratio', models.FloatField()),
                ('height_ratio', models.FloatField()),
                ('mask_key', models.IntegerField()),
                ('avg_depth', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('min_x', models.IntegerField()),
                ('max_x', models.IntegerField()),
                ('min_y', models.IntegerField()),
                ('max_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_data', to='db.video')),
            ],
            options={
                'ordering': ['video', 'timestamp', 'image_index', 'mask_key'],
                'indexes': [models.Index(fields=['video', 'timestamp'], name='db_displayd_video_i_8258b6_idx'), models.Index(fields=['image_index'], name='db_displayd_image_i_55538c_idx'), models.Index(fields=['avg_depth'], name='db_displayd_avg_dep_31f500_idx'), models.Index(fields=['description'], name='db_displayd_descrip_f4976d_idx')],
                'unique_together': {('video', 'image_index', 'mask_key')},
            },
        ),
    ]
