# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_video_summary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptsession',
            name='related_videos',
            field=models.ManyToManyField(
                blank=True,
                related_name='prompt_sessions',
                to='db.video'
            ),
        ),
    ]
