# Generated by Django 5.2 on 2025-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_depthdata_displaydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time_in_video',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
