# Generated by Django 5.2 on 2025-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_event_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
