# Generated by Django 5.2 on 2025-06-07 10:09

from django.db import migrations


def fix_first_response_data(apps, schema_editor):
    """
    기존의 잘못된 first_response 데이터를 수정합니다.
    각 PromptSession의 첫 번째 interaction의 output_response를 first_response로 설정합니다.
    """
    from django.db import connection
    
    # Raw SQL을 사용하여 안전하게 처리
    with connection.cursor() as cursor:
        # 먼저 필요한 필드들이 존재하는지 확인
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'db_promptsession' 
            AND column_name IN ('first_response', 'session_id')
        """)
        
        available_columns = [row[0] for row in cursor.fetchall()]
        
        if 'first_response' not in available_columns:
            print("first_response 필드가 아직 존재하지 않습니다. 스키마 마이그레이션을 먼저 실행해주세요.")
            return
        
        # first_response 필드 업데이트
        cursor.execute("""
            UPDATE db_promptsession 
            SET first_response = (
                SELECT output_response 
                FROM db_promptinteraction 
                WHERE db_promptinteraction.session_id = db_promptsession.session_id 
                ORDER BY timestamp ASC 
                LIMIT 1
            )
            WHERE EXISTS (
                SELECT 1 
                FROM db_promptinteraction 
                WHERE db_promptinteraction.session_id = db_promptsession.session_id
            )
        """)
        
        updated_count = cursor.rowcount
        print(f"PromptSession first_response 필드를 {updated_count}개 수정했습니다.")


def reverse_fix_first_response_data(apps, schema_editor):
    """
    이 마이그레이션을 되돌리는 함수입니다.
    실제로는 이전 상태를 복원할 수 없으므로 아무것도 하지 않습니다.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_video_video_file'),
    ]

    operations = [
        migrations.RunPython(fix_first_response_data, reverse_fix_first_response_data),
    ]
