# Generated by Django 5.2 on 2025-06-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_promptsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptinteraction',
            name='detected_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_interactions', to='db.event'),
        ),
    ]
