# Generated by Django 5.2 on 2025-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_promptinteraction_detected_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
