# Generated by Django 5.2 on 2025-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_video_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.IntegerField(max_length=255),
        ),
    ]
