# Generated by Django 5.2 on 2025-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_status',
            field=models.CharField(choices=[('pending', '대기중'), ('processing', '분석중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20),
        ),
    ]
