# Generated by Django 5.2 on 2025-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_video_analysis_progress_video_analysis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action_detected',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
