# Generated by Django 5.2 on 2025-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_event_action_detected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.IntegerField(),
        ),
    ]
