# Generated by Django 5.2 on 2025-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
